name: Docker CI reusable

on:
  workflow_call:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0

      - name: Build and start containers
        run: docker compose up -d --build

      - name: Wait for Spring Boot to become healthy
        run: |
          echo "Waiting for application to be ready..."
          for i in {1..30}; do
            if docker compose exec app curl -f http://localhost:8080/actuator/health; then
              echo "Application is healthy"
              exit 0
            fi
            echo "App not ready yet, retrying in 5 seconds..."
            sleep 5
          done
          echo "Application did not become healthy in time"
          docker compose logs app
          exit 1

      - name: Stop containers
        if: always()
        run: docker compose down
